version: '3.8'
services:
    db:
        image: 'postgres:latest'
        env_file:
            - .env
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
